### ISSUE TITLE
ejercicio 2

### ISSUE THREAD

**Issue by SandraCGarcia** [Adalab/dorcas-repaso-sprint2#3]
Buenos días Carlos,
He subido la segunda parte del ejercicio pero no consigo ver dónde está el error porque no funciona :(
Como me he atascado he seguido los pasos que habias hecho en tu ejercicio pero aun así no consigo ver que he hecho mal...

**Comment by oneeyedman** [comment]
Voy a verlo

**Comment by SandraCGarcia** [comment]
ya he visto el error, 
estaba aqui   const newsItem = document.querySelectorAll ('.news__item');
yo puse solo document.querySelector

**Comment by oneeyedman** [comment]
correcto!

**Comment by SandraCGarcia** [comment]
Hola Carlos,
he subido otra versión del ejercicio con DOM avanzado
